### PR TITLE
Add Difficulty option in Generating page

### PR DESCRIPTION
**Pull request by BLNDLYBLV**

### CODE REVIEW

**Comment by HemendraKhatik** [comment]
@BLNDLYBLV  can you please remove the conflicts then make a pull request again?

**Comment by BLNDLYBLV** [comment]
image
I think I cannot resolve conflicts without write access and i did not have any conflicts in my forked repo
So can you say what i must do now @HemendraKhatik

**Comment by HemendraKhatik** [comment]
just make 

> image
> I think I cannot resolve conflicts without write access and i did not have any conflicts in my forked repo
> So can you say what i must do now @HemendraKhatik

since you are 25 commits behind the master branch. Even it is difficult for me as well to resolve your conflicts.
just follow [this](https://stackoverflow.com/questions/41283955/github-keeps-saying-this-branch-is-x-commits-ahead-y-commits-behind) thread to fix this issue.

**Comment by BLNDLYBLV** [comment]
I changed and have given an another pr please check it

**Pull request closed without merging**
